### ISSUE TITLE
Avoid importing pyplot/pylab at runtime

### ISSUE THREAD

**Issue by keflavich** [cmcclellan1010/dendrocat#1]
This line:
https://github.com/cmcclellan1010/dendrocat/blob/678c40fd28f9bf8d6bf27102ff55df24f00da908/dendrocat/mastercatalog.py#L6

imports pylab/pyplot at import time.  It is best if that happens later, when a plotting function is called. e.g, you can add:
`import pyplot as plt`
into each of the functions that creates a plot.  This is helpful because importing pyplot can be expensive (it starts a GUI, depending on your settings), and dendrocat can be run without those gui tools (I think).

**Comment by cmcclellan1010** [comment]
Good tip! Resolved with [this](https://github.com/cmcclellan1010/dendrocat/commit/22cde46b7224e97cbb40b54a8ee6380b3773c8bd) commit.
